language: go
go_import_path: github.com/vapor
dist: trusty
sudo: false

matrix:
  include:
    - go: 1.11.4
    - go: tip
  allow_failures:
    - go: tip

branches:
    only:
        - master
        - dev

script:
    - make ci
