language: go
go_import_path: github.com/bytom/vapor
dist: trusty
sudo: false

matrix:
  include:
    - go: 1.11.4

branches:
    only:
        - master
        - dev
        - v0.1

script:
    - make ci
